### ISSUE TITLE
`NodePublishVolume` method

### ISSUE THREAD

**Issue by mbtamuli** [mbtamuli/csi-quickstart#25]

**Comment by mbtamuli** [comment]
Currently in #29, the implementation has this configuration
- A volume mounted from the host in both the plugin container and the `node-driver-registrar` container, which is used primarily for the CSI socket
    ```yaml
    spec:
      template:
        spec:
          containers:
            - volumeMounts:
                - mountPath: /csi
                  name: plugin-dir
          volumes:
            - hostPath:
                path: /var/lib/kubelet/plugins/emptydirclone.mriyam.dev
                type: DirectoryOrCreate
              name: plugin-dir
    ```
- The plugin creating a volume, that gets mounted at the target path as requested by kubelet. Now the path that the plugin uses for creating the volume lives under the path `/csi`
	```go
	// getVolumePath returns the canonical path for emptydirclone volume
	func getVolumePath(volName string) string {
		return filepath.Join("/csi/data", volName)
	}
	```

Although this works, the pattern I've seen is,
- A volume separate from the one used for the CSI socket mounted from the host in both the plugin container and the `node-driver-registrar` container
    ```yaml
    spec:
      template:
        spec:
          containers:
            - volumeMounts:
              - mountPath: /csi-data-dir
                name: csi-data-dir
        volumes:
          - hostPath:
              path: /var/lib/csi-emptydirclone.mriyam.dev-data/
              type: DirectoryOrCreate
            name: csi-data-dir
    ```
- The plugin uses the volume `/csi-data-dir/` to create all volumes within that path.


## ToDo
- Find out which is the actually acceptable and suggested path
